<?php

namespace Container6Bhw9yR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_11AyntUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.11AyntU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.11AyntU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'rep' => ['privates', 'App\\Repository\\TestQsRepository', 'getTestQsRepositoryService', true],
        ], [
            'rep' => 'App\\Repository\\TestQsRepository',
        ]);
    }
}
