<?php

namespace ContainerIo8FzeX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..l7u2Le.App\Entity\Tests' shared service.
     *
     * @return \App\Entity\Tests
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..l7u2Le": it references class "App\\Entity\\Tests" but no such service exists.');
    }
}
