<?php

namespace ContainerXeEa38U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestQsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KQ9CXi_.App\Entity\TestQs' shared service.
     *
     * @return \App\Entity\TestQs
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.KQ9CXi_": it references class "App\\Entity\\TestQs" but no such service exists.');
    }
}
