<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRxiMvU5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRxiMvU5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRxiMvU5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRxiMvU5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRxiMvU5\App_KernelDevDebugContainer([
    'container.build_hash' => 'RxiMvU5',
    'container.build_id' => '923bae34',
    'container.build_time' => 1681177265,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRxiMvU5');
